/* eslint-disable @next/next/no-img-element -- Native images preserve the authoritative HTML rendering exactly. */
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "./SiteChrome";
import { insightArticles } from "@/lib/insights";

const processSteps = [
  ["01", "Diagnóstico", "Analizamos el negocio, el usuario y el espacio para identificar oportunidades estratégicas."],
  ["02", "Estrategia", "Definimos el concepto que guiará cada decisión del proyecto."],
  ["03", "Diseño", "Desarrollamos la propuesta arquitectónica, el interiorismo y la estrategia de visual merchandising."],
  ["04", "Proyecto Ejecutivo", "Traducimos el concepto en documentación técnica lista para construirse."],
  ["05", "Ejecución", "Coordinamos y supervisamos cada etapa para asegurar que el proyecto se materialice conforme a la estrategia definida."],
  ["06", "Entrega Llave en Mano", "Un espacio preparado para operar, conectar con las personas y acompañar el crecimiento del negocio."],
] as const;

const solutions = [
  ["ABRIR UN NEGOCIO", "Desarrollamos conceptos comerciales desde cero, integrando arquitectura, identidad de marca y experiencia del cliente para construir espacios listos para crecer."],
  ["REMODELAR UN ESPACIO", "Replanteamos la distribución, la imagen y el funcionamiento de tu negocio para responder a nuevas necesidades y mejorar la experiencia de quienes lo visitan."],
  ["OPTIMIZAR EL DESEMPEÑO COMERCIAL", "Analizamos cómo las personas recorren e interactúan con tu espacio para identificar oportunidades de mejora en la circulación, exhibición y operación."],
] as const;

const projects = [
  ["/images/case1-hd.png", "Tienda de calzado diseñada por CRDN", "Concepto TERRA", "Retail · 2014 - 2024", "Calzado", "Concepto de tienda que se convitió en un estándar de marca por casi una década."],
  ["/images/case2-hd.png", "Boutique premium diseñada por CRDN", "Interiorismo y Visual Merchandising", "Retail · 2025", "Moda", "Proyecto que logró una experiencia de compra más clara, permitiendo exhibir un mayor volumen de producto de manera estratégica."],
  ["/images/case3-hd.png", "Módulo comercial diseñado por CRDN", "Módulo Comercial", "Comercial · 2023", "Activación", "Una solución modular para punto de encuentro para clientes y activaciones de marca en espacios temporales."],
] as const;

function ContactIcon({ type }: { type: "phone" | "email" | "whatsapp" | "instagram" }) {
  if (type === "phone") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" /></svg>;
  if (type === "email") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="16" x="2" y="4" rx="2" /><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" /></svg>;
  if (type === "whatsapp") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"><path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" /></svg>;
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="20" x="2" y="2" rx="5" ry="5" /><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" /><line x1="17.5" x2="17.51" y1="6.5" y2="6.5" /></svg>;
}

export function LandingContent() {
  return <main id="content">
    <section className="hero" id="home"><div className="shell hero__inner">
      <div className="hero__meta"><p className="eyebrow">CRDN — retail, brand &amp; commercial design</p><p className="eyebrow eyebrow--est">León. Guanajuato · México</p></div>
      <span className="hero__rule" aria-hidden="true" />
      <h1 className="hero__title"><span className="line-mask"><span className="line-mask__inner">Tu espacio también</span></span><span className="line-mask"><span className="line-mask__inner"><em>forma parte de tu estrategia de negocio.</em></span></span></h1>
      <div className="hero__lede"><p className="hero__support reveal" data-delay="1">Combinamos arquitectura comercial, interiorismo y visual merchandising para convertir cada metro cuadrado en una herramienta estratégica que fortalece la experiencia del cliente y el valor de tu negocio.</p><div className="hero__ctas reveal" data-delay="2"><a className="btn btn--solid" href="#contact">Iniciar Proyecto <ArrowRight /></a><a className="btn btn--ghost" href="#projects">Ver Proyectos <ArrowRight /></a></div></div>
      <div className="hero__plate reveal" data-delay="2"><figure className="plate" style={{ margin: 0 }}><div className="plate__frame ar-hero"><img src="/images/heroimg-hd.png" alt="Espacio comercial diseñado por CRDN" /></div><figcaption className="plate__caption"><span className="eyebrow" /></figcaption></figure></div>
      <div className="hero__foot reveal" data-delay="3"><p className="eyebrow">CRDN</p><p className="eyebrow eyebrow--mid">§ 01</p><a className="hero__scroll" href="#about" aria-label="Bajar a la sección de estudio"><span className="eyebrow">Explorar</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M12 5v14M6 13l6 6 6-6" /></svg></a></div>
    </div></section>

    <section className="section bg-plaster" id="about"><div className="shell">
      <div className="reveal"><div className="section-head__rule"><span className="eyebrow">§ 02</span><span className="line" aria-hidden="true" /><span className="eyebrow">El estudio</span></div><h2 className="section-head__title">El espacio es <em>el mejor vendedor de tu marca.</em></h2></div>
      <div className="about__grid"><div className="about__portrait reveal" data-delay="1"><figure className="plate" style={{ margin: 0 }}><div className="plate__frame about__logo-frame"><Image src="/images/crdn-wordmark-cropped.png" alt="Equipo de CRDN" width={1050} height={300} sizes="(max-width: 1023px) calc(100vw - 3rem), (max-width: 1439px) calc(50vw - 4rem), 40rem" quality={100} /></div><figcaption className="plate__caption"><span className="eyebrow">CRDN - retail, brand &amp; commercial design</span></figcaption></figure></div>
        <div className="about__body"><div className="reveal"><p className="about__lead">CRDN es un estudio de diseño comercial. Proyectamos retail, interiorismo y experiencias de marca donde cada decisión de espacio, luz y material responde a un objetivo de negocio.</p><p className="about__text">Hemos desarrollado más de 370 espacios comerciales en México. Lo que nos define no es un estilo, sino un método: entender el negocio antes de dibujar y cuidar cada detalle hasta la ejecución.</p></div><div className="reveal" data-delay="1"><blockquote className="about__quote"><p>“Un buen espacio no se nota; se siente — y se traduce en ventas.”</p></blockquote></div><div className="reveal" data-delay="1"><dl className="about__facts"><div className="about__fact"><dt className="eyebrow">Experiencia</dt><dd>15+ años</dd></div><div className="about__fact"><dt className="eyebrow">Sede</dt><dd>León, GTO</dd></div><div className="about__fact"><dt className="eyebrow">Espacios</dt><dd>370+</dd></div><div className="about__fact"><dt className="eyebrow">Sectores</dt><dd>12+</dd></div></dl></div><div className="reveal" data-delay="2"><div className="about__spec"><p className="eyebrow">Especialidades</p><ul><li><span>Arquitectura comercial</span><span className="eyebrow">01</span></li><li><span>Interiorismo</span><span className="eyebrow">02</span></li><li><span>Visual merchandising</span><span className="eyebrow">03</span></li><li><span>Branding espacial</span><span className="eyebrow">04</span></li></ul></div></div></div>
      </div>
    </div></section>

    <section className="section" id="solutions"><div className="shell"><div className="reveal"><div className="section-head__rule section-head__rule--centered"><span className="eyebrow">§ 03</span><span className="line" aria-hidden="true" /><span className="eyebrow">Soluciones</span></div><h2 className="section-head__title section-head__title--centered">Soluciones.</h2><p className="section-head__tagline section-head__tagline--centered">Diseñamos estrategias para cada etapa de tu negocio</p><p className="section-head__tagline section-head__tagline--centered">¿Cuál es tu momento?</p></div><div className="card-grid card-grid--3">{solutions.map(([title, quote], index) => <figure className="testi-card reveal" data-delay={index} style={{ margin: 0 }} key={title}><figcaption className="solutions-card__title">{title}</figcaption><blockquote className="testi-card__quote">{quote}</blockquote><div className="testi-card__foot"><p className="testi-card__name" /></div></figure>)}</div></div></section>

    <section className="section bg-plaster" id="projects"><div className="shell"><div className="reveal"><div className="section-head__rule"><span className="eyebrow">§ 04</span><span className="line" aria-hidden="true" /><span className="eyebrow">Proyectos</span></div><h2 className="section-head__title">Resultados que hablan por sí solos.</h2><p className="section-head__tagline">Casos de éxito que demuestran el impacto de nuestra metodología en el diseño comercial y en la conducta de los clientes dentro del espacio.</p></div><div className="card-grid card-grid--3">{projects.map(([image, alt, title, date, sector, summary], index) => <Link className="project-card reveal" data-delay={index} href={`/projects#proyecto-${index + 1}`} key={title}><div className="project-card__media"><img src={image} alt={alt} /></div><div className="project-card__head"><h3 className="project-card__title">{title}</h3><span className="project-card__arrow"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10" /></svg></span></div><p className="project-card__meta"><span className="eyebrow">{date}</span><span className="eyebrow">{sector}</span></p><p className="project-card__summary">{summary}</p></Link>)}</div><div className="section__foot-cta reveal"><Link className="btn btn--outline" href="/projects">Ver todos los proyectos <ArrowRight /></Link></div></div></section>

    <section className="section" id="process"><div className="shell"><div className="reveal"><div className="section-head__rule"><span className="eyebrow">§ 05</span><span className="line" aria-hidden="true" /><span className="eyebrow">Metodología</span></div><h2 className="section-head__title">METODOLOGÍA.</h2><p className="section-head__tagline">Un proceso probado en más de 370 espacios comerciales.</p></div><ol className="process__list"><span className="process__spine" aria-hidden="true" />{processSteps.map(([number, title, description]) => <li className="process__step" key={number}><span className="process__dot" aria-hidden="true" /><div className="process__row reveal"><div className="process__num-wrap"><p className="process__num" aria-hidden="true">{number}</p></div><div className="process__title-wrap"><h3 className="process__title">{title}</h3></div><p className="process__desc">{description}</p></div></li>)}</ol><p className="process__closing reveal">Cada proyecto tiene un objetivo común: transformar el espacio en una herramienta estratégica para la marca.</p></div></section>

    <section className="section--tight bg-night section--dark" aria-label="CRDN en números"><div className="shell"><div className="reveal"><div className="section-head__rule"><span className="eyebrow">CRDN</span><span className="line" aria-hidden="true" /><span className="eyebrow">En números</span></div></div><dl className="stats__grid"><div className="stat reveal" data-delay="0"><dd className="stat__value"><span data-count="15" data-suffix="+">0</span></dd><dt className="stat__label eyebrow">Años de Experiencia</dt></div><div className="stat reveal" data-delay="1"><dd className="stat__value"><span data-count="370" data-suffix="+">0</span></dd><dt className="stat__label eyebrow">Espacios Desarrollados</dt></div><div className="stat reveal" data-delay="2"><dd className="stat__value"><span data-count="12" data-suffix="+">0</span></dd><dt className="stat__label eyebrow">Sectores Atendidos</dt></div></dl></div></section>

    <section className="section" id="insights"><div className="shell"><div className="reveal"><div className="section-head__rule"><span className="eyebrow">§ 06</span><span className="line" aria-hidden="true" /><span className="eyebrow">Insights</span></div><h2 className="section-head__title">Ideas sobre espacio, marca y comercio.</h2><p className="section-head__tagline">Nuestro journal editorial sobre diseño comercial, retail y la relación entre arquitectura y negocio.</p></div><div className="card-grid card-grid--4">{insightArticles.map((article, index) => <Link className="article-card reveal" data-delay={index} href={`/insights/${article.slug}`} key={article.slug}><div className="article-card__media"><img src={article.featuredImage} alt={article.images.find((image) => image.src === article.featuredImage)?.alt ?? ""} /></div><div className="article-card__meta"><span className="eyebrow">{article.category}</span><span className="eyebrow">{article.date}</span></div><h3 className="article-card__title">{article.title}</h3><p className="article-card__excerpt">{article.excerpt}</p><span className="article-card__cta">Leer artículo <ArrowRight /></span></Link>)}</div></div></section>

    <section className="section bg-sand" id="contact"><div className="shell"><div className="reveal"><div className="section-head__rule"><span className="eyebrow">§ 07</span><span className="line" aria-hidden="true" /><span className="eyebrow">Contacto</span></div><h2 className="section-head__title">Todo gran proyecto comienza con una buena conversación.</h2></div><p className="contact__support reveal" data-delay="1">Cuéntanos qué quieres lograr; diseñaremos una estrategia espacial que fortalezca tu marca, conecte con las personas y aporte valor a tu negocio.</p><ul className="contact__grid" style={{ listStyle: "none", padding: 0 }}><li className="reveal" data-delay="0"><a className="contact__item" href="tel:+524774088056" aria-label="Teléfono: 477 408 80 56"><span className="contact__icon"><ContactIcon type="phone" /></span><span><span className="contact__label eyebrow">Teléfono</span><span className="contact__value">477 408 8056</span></span></a></li><li className="reveal" data-delay="1"><a className="contact__item" href="mailto:comercial@crdnarquitectura.com" aria-label="Email: comercial@crdnarquitectura.com"><span className="contact__icon"><ContactIcon type="email" /></span><span><span className="contact__label eyebrow">Email</span><span className="contact__value">comercial@crdnarquitectura.com</span></span></a></li><li className="reveal" data-delay="2"><a className="contact__item" href="https://wa.me/525542108800" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp: escríbenos"><span className="contact__icon"><ContactIcon type="whatsapp" /></span><span><span className="contact__label eyebrow">WhatsApp</span><span className="contact__value">Escríbenos</span></span></a></li><li className="reveal" data-delay="2"><a className="contact__item" href="https://instagram.com/crdnarquitectura" target="_blank" rel="noopener noreferrer" aria-label="Instagram: @crdnarquitectura"><span className="contact__icon"><ContactIcon type="instagram" /></span><span><span className="contact__label eyebrow">Instagram</span><span className="contact__value">@crdnarquitectura</span></span></a></li></ul><p className="contact__addr eyebrow reveal">León, Guanajuato, México — visitas con cita previa</p></div></section>
  </main>;
}
